version: "3.8"


services:
    django:
        build: .
        container_name: django
        command: > 
            sh -c "python manage.py makemigrations users &&
                   python manage.py makemigrations table &&
                   python manage.py migrate &&
                   python make_webhook_firstly.py &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports: 
            - "8000:8000"
        depends_on:
            - pycab_db
            - redis
            - smtp-server
    pycab_db:
        image: postgres
        container_name: pycab_db
        environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
          - '5432'
        ports:
          - '5105:5432'
    redis:  
        image: redis
        container_name: redis
        ports:
        - "6379"
        restart: always
    smtp-server:
        image: mailhog/mailhog
        expose:
            - 1025
            - 8025
        ports:
            - '1025:1025'
            - '8025:8025'
    celery:
        build: .
        command: celery -A pycab worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
#        volumes:
#        - ./redis.conf:/usr/local/etc/redis/redis.conf

