name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Restart services
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 46.254.21.179
          username: root
          key: ${{ secrets.POPSO_DELETE_FOR_TEST }}
          # comment just for new push
          script: |
            pwd


    