name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Test new kitty
    runs-on: ubuntu-latest
    steps:
      - name: Create secret file
        run: echo "${{ secrets.MACHINE_ROOT_PASSWORD }}" > secret.txt
      - name: Show secret from file
        run: cat secret.txt
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 81.31.244.30
          username: root
          password: cM7-eN8^3g8*-.
          port: ${{ secrets.PORT }}
          script: |
            ls -al
            whoami
            cd /home
            git init
            git remote add pycab_repo https://github.com/romashovdmitry/pycab_django_v.git
            git fetch -all
            git checkout deleteme --force
            git pull