name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: test new kitty
    runs-on: ubuntu-latest
    steps:
      - name: Create secret file
        run: echo "${{ secrets.MACHINE_ROOT_PASSWORD }}" > secret.txt
      - name: Show secret from file
        run: cat secret.txt
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 81.31.244.30
          username: root
          password: ${{ secrets.MACHINE_ROOT_PASSWORD }}.
          port: ${{ secrets.PORT }}
          script: |
                ls -al
                whoami

