name: Send File to Remote Server GPT version

on:
  push:
    branches:
      - master

jobs:
  send-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: huepezda
        run: echo ${{ secrets.SSH_IP_ADRESS }}

      - name: pezdahue
        run: echo ${{ env.SSH_PRIVATE_KEY }}

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
          
      - name: Create file
        run: echo "hello world" > file.txt
        
      - name: Copy file to remote server
        run: scp -i ${{ env.SSH_PRIVATE_KEY }} file.txt root@${{ secrets.SSH_IP_ADRESS }}:/etc/file.txt
