name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Copy repo files to remote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Create .env file
        run: |
            echo "SECRET_KEY=HUEPEZDA" >> .env
      - name: Copy repo files to remote
#        uses: appleboy/ssh-action@master
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 77.73.132.55
          username: root
          key: ${{ secrets.LAST_ONE_SSH_PRIVATE_KEY }}
          port: 22
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "test.txt"
          target: '/home'
          overwrite: true

# выводило список файлов. не отправляло файлы. 
#          script: |
#                  ls -al
#                  whoami
# rsync -avz --progress $GITHUB_WORKSPACE/ root@77.73.132.55:/



#script: |
#            ls -al
