name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
      - name: Restart services
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 46.254.21.179
          username: root
          key: ${{ secrets.POPSO_DELETE_FOR_TEST }}
          passphrase: pop1m2bx7!j
          script: |
            echo "Before command"
            pwd
            echo "After command"