name: Pycab Deploy

on:
  push:
    branches:
      - master

jobs:
  make_env:
    name: Create and update .env file on remote server
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote server and create/update .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP_ADRESS }}
          username: ${{ secrets.REMOTE_ROLE }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "KEY=value" > /var/.env
