name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Copy repo files to remote
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 81.31.244.30
          username: root
          password: ${{ secrets.MACHINE_ROOT_PASSWORD }}.
          port: ${{ secrets.PORT }}
          script: |
                ls -al
                whoami

