name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
      name: Copy repo files to remote
      runs-on: ubuntu-latest
      steps:
      - name: Copy repo files to remote
        uses: appleboy/ssh-action@master
        with:
          host: 77.73.132.55
          username: root
          key: ${{ secrets.LAST_ONE_SSH_PRIVATE_KEY }}
          port: 22
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            scp -r "."  root@77.73.132.55:/root/dmitry/git_test_delete
