# Generated by Django 4.1 on 2023-05-15 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=256, verbose_name='Word')),
                ('definition', models.CharField(max_length=2048, null=True, verbose_name='Definition')),
                ('status_of_word_in_whole', models.CharField(blank=True, max_length=10, null=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'db_table': 'vocab',
                'unique_together': {('word', 'definition')},
            },
        ),
        migrations.CreateModel(
            name='DynamicVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_dynamic', models.CharField(max_length=256)),
                ('definition_dynamic', models.CharField(blank=True, max_length=2048)),
                ('status_of_word_dynamic', models.CharField(max_length=10, null=True)),
                ('id_dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.vocab')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'db_table': 'dynamic_vocab',
            },
        ),
    ]
