# Generated by Django 4.1 on 2023-02-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='dynamicvocab',
            table='dynamic_vocab',
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
        migrations.AlterModelTable(
            name='wholevocab',
            table='whole_vocab',
        ),
    ]
